### ISSUE TITLE
Unable to emerge cnijfilter-4.10

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [tokiclover/bar-overlay#17]
Today emerge -uDN @world wants to rebuild cnijfilter, without the mx530 use flag for some reason:
Andrew-Gentoo ~ # emerge -uDN @world

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   ~] net-print/cnijfilter-4.10  USE="(-e400%) (-e560%) (-ip2800%) (-ip8700%) (-ix6700%) (-ix6800%) (-mx470%) (-mx530%*)" 

Would you like to merge these packages? [Yes/No] n  

When I allow emerge to do this it stops with the following error:
Failed to emerge net-print/cnijfilter-4.10, Log file:

 '/var/tmp/portage/net-print/cnijfilter-4.10/temp/build.log'

  Messages for package net-print/cnijfilter-4.10:

  ERROR: net-print/cnijfilter-4.10::bar failed (prepare phase):
    USE Flag 'ix6700' not in IUSE for net-print/cnijfilter-4.10
  
  Call stack:
           ebuild.sh, line   93:  Called src_prepare
         environment, line 3590:  Called ecnij_src_prepare
         environment, line 1243:  Called use 'ix6700'
    phase-helpers.sh, line  200:  Called die
  The specific snippet of code:
                               die "USE Flag '${u}' not in IUSE for ${CATEGORY}/${PF}"
 
 If you need support, post the output of `emerge --info '=net-print/cnijfilter-4.10::bar'`,
 the complete build log and the output of `emerge -pqv '=net-print/cnijfilter-4.10::bar'`.
 The complete build log is located at '/var/tmp/portage/net-print/cnijfilter-4.10/temp/build.log'.
 The ebuild environment file is located at '/var/tmp/portage/net-print/cnijfilter-4.10/temp/environment'.
 Working directory: '/var/tmp/portage/net-print/cnijfilter-4.10/work/cnijfilter-source-4.10-1'
 S: '/var/tmp/portage/net-print/cnijfilter-4.10/work/cnijfilter-source-4.10-1'

Andrew-Gentoo andrew # emerge --info '=net-print/cnijfilter-4.10::bar' | wgetpaste
Your paste can be seen here: https://bpaste.net/show/14b5b076f5c6
Andrew-Gentoo andrew # emerge -pqv '=net-print/cnijfilter-4.10::bar' | wgetpaste
Your paste can be seen here: https://bpaste.net/show/4cc61d34bc4d
Andrew-Gentoo andrew # cat /var/tmp/portage/net-print/cnijfilter-4.10/temp/build.log | wgetpaste
Your paste can be seen here: https://bpaste.net/show/5f92ebddeb11

I think emerge stops because now no printer model is set, I tried setting others but the result is the same. I do need the mx530 use flag, but it seems to be masked together with other use flags for version 4.10.

**Comment by tokiclover** [comment]
On Mon, Aug 17, 2015 at 12:33:55AM -0700, Andrew Ammerlaan wrote:
> Today emerge -uDN @world wants to rebuild cnijfilter, without the mx530 use flag for some reason:
> Andrew-Gentoo ~ # emerge -uDN @world
> 
> These are the packages that would be merged, in order:
> 
> Calculating dependencies... done!
> [ebuild   R   ~] net-print/cnijfilter-4.10  USE="(-e400%) (-e560%) (-ip2800%) (-ip8700%) (-ix6700%) (-ix6800%) (-mx470%) (-mx530%*)" 
> 
Darn... just forgot to test before pushing and then forgot an extra
unnecessary S in PRINTERS_MODEL env-var in the appropriate eclass?

Note that, the printer USE flags has now `canon_printers_` prefix!
So, adjust your printer USE flags or set `CANON_PRINTERS="mx530"`
in `/etc/portage/make.conf` configuration file.

This change is half cosmetic... however, I find it clearer to have
that prefix before those numerous USE flags related to printer models.

Thanks for reporting. It's now fixed in the tree.

**Comment by tokiclover** [comment]
```
[ebuild   R    ] net-print/cnijfilter-4.10:4::bar  USE="backends doc gtk net usb -canon_printers_e400% -canon_printers_e560% -canon_printers_ip2800% -canon_printers_ip8700% -canon_printers_ix6700% -canon_printers_ix6800% -canon_printers_mx470% -canon_printers_mx530% -debug -drivers -servicetools (-e400%) (-e560%) (-ip2800%) (-ip8700%) (-ix6700%) (-ix6800%) (-mx470%) (-mx530%)" ABI_X86="(64) -32" 0 KiB
```

**Comment by AndrewAmmerlaan** [comment]
Well that fixes the problem with the use flag, but emerge still fails with the same error. The use flag is now set correctly and emerge shows it as enabled, but the error in my original post remains.

**Comment by tokiclover** [comment]
Right... fiexed with 5c22584. -- Previous typo fix was half of the story.

**Comment by AndrewAmmerlaan** [comment]
Awesome, thanks for fixing on such a short notice.
